<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23236" started-at="2020-03-19T19:19:19Z" finished-at="2020-03-19T19:19:42Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23236" started-at="2020-03-19T19:19:19Z" finished-at="2020-03-19T19:19:42Z">
      <class name="UITestCases.TC01_verifyLogin">
        <test-method status="PASS" signature="setUp()[pri:0, instance:UITestCases.TC01_verifyLogin@23ceabc1]" name="setUp" is-config="true" duration-ms="5015" started-at="2020-03-20T00:49:19Z" finished-at="2020-03-20T00:49:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="VerifyRegistration()[pri:0, instance:UITestCases.TC01_verifyLogin@23ceabc1]" name="VerifyRegistration" duration-ms="13314" started-at="2020-03-20T00:49:24Z" finished-at="2020-03-20T00:49:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyRegistration -->
        <test-method status="FAIL" signature="VerifySignIn()[pri:0, instance:UITestCases.TC01_verifyLogin@23ceabc1]" name="VerifySignIn" duration-ms="4885" started-at="2020-03-20T00:49:37Z" finished-at="2020-03-20T00:49:42Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<...3> but was:<...>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<...3> but was:<...>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at UITestCases.TC01_verifyLogin.VerifySignIn(TC01_verifyLogin.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifySignIn -->
      </class> <!-- UITestCases.TC01_verifyLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
